Feature: Work Entry Generation, Validation, and Types
  As an HR Manager
  I want to generate and validate work entries
  So that payroll can use correct working time data

  Background:
    Given I am logged in as an HR manager
    And the employee "John Doe" exists
    And the company "Tech Corp" uses work entry generation

  Scenario: Employee reports whether work entries exist
    Given an employee with generated work entries
    When I compute has_work_entries
    Then the flag should be True

  Scenario: Open work entries action filters by employee and date
    Given an employee with work entries in January
    When I open work entries from the employee
    Then the action should show the work entries list filtered to that employee

  Scenario: Generate work entries for a date range
    Given a contract and attendance data for January
    When I generate work entries from 2025-01-01 to 2025-01-31
    Then work entries should be created for the period

  Scenario: Generate work entries can be forced
    Given existing work entries in the period
    When I generate work entries with force=True
    Then the work entries should be regenerated

  Scenario: Work entry display name includes type and time span
    Given a work entry of type "Normal Work"
    When I compute the display name
    Then the display name should reflect the work entry type and timing

  Scenario: Work entry name is derived from the source interval
    Given a work entry interval from attendance
    When I compute the name
    Then the name should be populated from the interval data

  Scenario: Duration must be positive and at most 24 hours
    When I create a work entry with duration 0 or 25
    Then a validation error should be raised

  Scenario: Work entry validates successfully
    Given a draft work entry
    When I validate it
    Then the state should become validated

  Scenario: Work entry split creates a derived entry
    Given a work entry that must be split across dates
    When I split the work entry
    Then a new work entry should be created for the split interval

  Scenario: Work entry conflict detection marks conflicting records
    Given overlapping work entries for the same employee
    When the conflict check runs
    Then the conflicting entries should be marked as conflict

  Scenario: Conflicting work entries can be reset
    Given a work entry marked as conflict
    When I reset conflicting state
    Then the work entry should return to a non-conflict state

  Scenario: Work entry unlink is blocked for non-validated entries
    Given a draft work entry
    When I try to delete it
    Then deletion should be prevented unless the state is allowed

  Scenario: Work entry country search resolves employee country
    When I search work entries by country
    Then the domain should resolve using the employee country relation

  Scenario: Work entry type uniqueness is enforced by code
    Given two work entry types with the same code
    When I try to save them
    Then a validation error should be raised

  Scenario: Work entry type country constraint is enforced
    Given a work entry type linked to a country
    When I assign it to an incompatible company setup
    Then a validation error should be raised

  Scenario: Work entry type work flag is mirrored by is_work
    Given a work entry type marked as work
    When I compute is_work
    Then the work flag should be consistent

  Scenario: Resource calendar attendance defaults its work entry type
    Given a resource calendar attendance line
    When I create it
    Then the default work entry type should be assigned

  Scenario: Calendar leaves copy their work entry values
    Given a resource calendar leave interval
    When I copy the leave values
    Then the work entry fields should be preserved

  Scenario: Missing work entries can be generated by cron
    Given there are gaps in expected work entries
    When the cron runs
    Then missing work entries should be generated automatically
